### PR TITLE
Added heart icon instead of upvote label

### PR DESCRIPTION
**Pull request by bikingbadger**
Changed the upvote label to a heart icon. Small change requested from Dawid as a good first request. This is my first PR so would appreciate any direction for how to improve it for merging.

### CODE REVIEW

**Comment by thedc89** [comment]
Hi @bikingbadger! Thanks for this PR. We'll review it this week!

**Comment by bikingbadger** [comment]
Hi @ArkuVonSymfon 
Made the change like you requested. Changed to using a svg and also managed to even change the color of the heart. I see it is filling correctly. I also made a change to the hover which just looked a bit arbitrary. Let me know if anything else is needed.

**Comment by thedc89** [comment]
Looks awesome! @andrewmarklloyd I think we can merge it :)

**Comment by andrewmarklloyd** [comment]
Nice work @bikingbadger and thanks @thedc89 and @ArkuVonSymfon for the reviews!

**Pull request merged**
