### PR TITLE
Move to vuetify for layout and component styles

### PR DESCRIPTION
**Pull request by dfcook**
Hopefully this is of use to the project, I've been looking at the code and made some changes which I think add to the overall structure:

1. Updated all npm packages to latest versions
2. Removed reference to jquery and bootstrap. 
3. Used vuetify throughout for layout and component styles. v-validate integration for form validation.
4. Added support files for flow when using VS Code as an editor.
5. Use object props declarations for components to allow for prop validation.

### CODE REVIEW

**Comment by crablar** [comment]
@dfcook this looks great--going to wait for Jason to take a look when he gets back from vacation.

**Comment by ghenry** [comment]
How do I checkout just this merge request/version @dfcook?

**Comment by dfcook** [comment]
I think you just clone my version of the repository:

https://github.com/dfcook/sedaily-front-end

**Comment by ghenry** [comment]
Ah, couldn't find that in the MR ticket.

**Comment by ghenry** [comment]
Got it now. I'm finding the modal's to be a bit stuttery on Firefox Quantum and is there a reason not to use history mode on vue-router?

**Comment by dfcook** [comment]
No reason not to use history mode, I've just tried it and it seems OK, I can include it in my next commit.

Interesting about firefox, I have it on my dev machine (a Linux laptop) and the family PC (Windows 10) and am not seeing any stuttering. What's your platform?

**Comment by ghenry** [comment]
I'll get a wee vid together.

**Comment by dfcook** [comment]
I’ve setup a codepen with a simple vuetify dialog, could you try this as well to see if it’s the dialog itself or how I’m using it:

https://codepen.io/dfcook/pen/eyWOQB


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ghenry** [comment]
That looks fine. The local demo has the issue.
[modal.zip](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/files/1593061/modal.zip)

**Comment by ghenry** [comment]
In fact, then I made the codepen full screen, I get the same effect.

**Comment by dfcook** [comment]
Sure, I've joined now.

**Comment by jasonify** [comment]
Thanks for doing this, it's amazing work. As discussed on slack going to close this one and wait for an updated version when you are ready. Feel free to reopen / create a new PR then.

**Pull request closed without merging**
