### PR TITLE
General refactor

### LINKED ISSUE #43: Research better way to make Vue state access more friendly
I believe Vue has a few helper functions / patterns to not have code like this:
```
  computed: {
     postId () {
        return this.$store.state.items[this.$route.params.id]
      }
 }
```

### PR DESCRIPTION
**Pull request by EmilyRosina**
Namely picked up as saw #43 issue about mapState and thought i'd give it a whirl.

Then once in found myself doing some general tidying in...
- component markup
- methods
- getters
- mapState
- mapGetters
- mapActions

I also added a bit of layout styling to the contributors view, as well as each contributers avatar 👍 

Closes #43

### CODE REVIEW

**Comment by jasonify** [comment]
Hey @EmilyRosina  thanks for you PR and welcome!

I haven't had a chance to go through your PR yet, sorry about that. 


Generally for such a big refactor we would run through this list: https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/ManualTestingChecklist.md
Did you get a chance to do that yet? I would merge your code with develop to make sure it's up to date.


We have done a bad job at this but in general we prefer smaller PRs, sorry for not communicating that in our guide.


Let's see if we can't get this merged in though :)

**Comment by EmilyRosina** [comment]
Hi @jasonify & @crablar, been afk for a little while - but ty for the replies.

I can't see an easy way for me to resubmit as smaller PR's than just doing it all again.
Watch this space...

**Comment by jasonify** [comment]
@EmilyRosina  Are you on slack?

Might be easier to discuss potential issues and features on there.

**Comment by EmilyRosina** [comment]
@jasonify good shout - just joined 👍

**Pull request closed without merging**
