### PR TITLE
cypress for integration/e2e tests

### PR DESCRIPTION
**Pull request by joshmorel**
@jasonify  - After hearing about it in our Slack I looked more into [cypress](https://www.cypress.io/) and was extremely impressed with the docs.

Tried to get it to work and have so far been impressed with usability and functionality. It's a super large package, but pretty comprehensive and feature rich. Take a look and let me know if this is a good go forward option and I'll put more work into it. 

So far you'll need to run `npm run dev` in one terminal and `npm run cy:open` in another to see how it works. It's possible to run them both together but it would require some tweaking of the webpack configs.

### CODE REVIEW

**Comment by jasonify** [comment]
Nice. 

This does look nice and pretty cool :).

I'm up for trying it.

**Comment by joshmorel** [comment]
Hey @jasonify . Significant progress this weekend, but a lot focused on the webpack config... Because I needed to change Webpack anyways I merged #318 and went a lot further - refactoring the build/config to comprise only what we need while re-organizing it into two files `webpack.config.js` and `webpack.parts.js`. The approach is borrowed from the [Webpack book](https://survivejs.com/webpack/) and, at least to me, results in something easier to understand and modify compared to what we started with from vue cli. 

There is probably opportunity to optimize JS output further and if we're going to be bundling bootstrap etc we can probably make more deliberate choices about fonts, but this can be done later.

One thing that I haven't gotten to work with webpack 4 is karma-webpack. However, I'm not sure if we'll need it anymore. Currently it's used for unit tests, but I feel that if we have comprehensive integration testing with cypress that's not necessary. This is my suggestion for what should comprise testing:

1) *e2e tests*: True end-to-end tests which include a real back-end. Should be limited to [some key processes to keep things manageable](https://docs.cypress.io/guides/getting-started/testing-your-app.html#Stubbing-the-Server). Back-end is run using `start:e2e` - see [related branch](https://github.com/joshmorel/software-engineering-daily-api/tree/support-cypress-testing) - which can be done manually or with CI.  
2) *integration tests*: Test integration of browser with front-end code base run from a dev-server. The back-end server is mocked. Unlike e2e, intended to cover all functionality.
3) *unit tests*: Testing units of function - which is tricky with Vue and requires awkward workarounds. If 2 is followed, it's also not necessary. Unit testing on top of integration/e2e testing would add complexity to the project set-up while not adding any value. 

If you're fine with this, now that I've got the build down It's just about adding more tests. I'll create integration for everything captured in the units tests and more.

**Comment by jasonify** [comment]
Cool, my general preference is to not modify the build system as much as possible but I think it's worthwhile for this.


Overall I think it would be wise to make it simple for new contributors to run the tests.


Personally I think #1 is what really matters.  #3 I am not entirely convinced we need. 

I think having the testing commands point to staging by default would be a good first start. But also allowing the option to test e2e locally is good. There is one downside to using staging which is that testing things like order of a forum post being at the top after being posted is not guaranteed (if we assume everyone is using staging at the same time). There is also the problem of the staging server getting broken. 


So I see your point as to why we should focus on #2. The one problem is, it's yet another thing to keep updating and adds an extra step to writing tests, though it does make them easier to run.


Brainstorming:
- I guess a cool thing would be if we had a service to see if someone else is running tests on staging and if so then just wait? This wouldn't be too difficult to implement. Would probably be fine for a little while. I we wanted extra options we could just have a dedicated backend test server that we could clear every time. 

- A set of scripts to make it super easy to setup your local backend env. Pings 4040. 


Having this hooked up to Travis would also be pretty key.


Right now I am really leaning towards the staging-backend test idea... I know it would mean we would write tests in a different manner but I think that's okay. 


I want to take some more time to think though. Let me know your thoughts.

**Comment by joshmorel** [comment]
Really great feedback and ideas @jasonify . I do like your idea about only worrying about one kind of 
testing for the front-end - 1) e2e. It would make the decision path straight forward with regards to how to test a piece of new functionality.

I kept thinking of ways of making staging work... But there are just so many complications. It would absolutely need to be deterministic - meaning one set of tests could not be affected by side affects by another user testing. Which means we'd also need a REST request to drop & seed the database. Even if you work that into the code base to never occur in production that still makes me nervous. Also there are other considerations that you mention with regards to the server being unavailable and also speed - the test suite could get slow as it grows due to latency.

This makes me think that staging should be for usability testing, and a local back-end for e2e testing. Let me know if I'm missing anything or if you think of something else.

At first I can design it so it must be run manually, then add the automation later. Likely Docker is the right choice for this and this *should* work nicely with Travis CI. There may be some additional maintenance headaches with Docker but nothing that is a show stopper.

I'm happy to keep chipping away at this. For the webpack build, I'll make sure the result is the same as whatever `develop` is at when I merge it in. The config refactor was simply to enable this while at the same time make the webpack code more easily understandable and extensible when future modifications are necessary.

**Comment by jasonify** [comment]
All that makes sense, especially about not wanting to have stuff potentially drop the DBs in production.

My idea for staging or rather, the dedicated testing server would be:

1) Your concern is a valid one that I also have but what I was thinking is we could write helper scripts that are not part of the backend-repo. It's similar to the `mining scripts`. We plug-in the credentials to the testing DB we want to modify and it will just reset the data using `monk`, see  https://github.com/SoftwareEngineeringDaily/sedaily-miner/blob/master/getMp3.js

While we could make mistakes and clear the prod DB , as long as we realize it pretty soon, we have daily backups for prod.  And that's only if you have credentials to that DB, which most people wouldn't. Though it does leave the testing server open to everyone which is a concern but I believe that should be okay and if we have a big problem with that, we can look into it. If we have a  real problem, we might only use the testing server through Travis CI.

2) Maybe overkill?  Write an endpoint called `/e2e/start` and it would just set a value in the DB that stuff is being tested and return true if it is and when it started. So a `bool` and a `timestamp`.  We can then write helper local scripts. [Optional] `/e2e/end` Maybe have the start endpoint also return a token you can use to end your test.. that way we can match and see if your tests finished, but use the timestamps to make a best guess (i.e if it started 1hr ago but it didn't finish we can assume the users computer probably had a problem).

3) Yeah, been thinking Docker but it seems many people have had problems setting it up especially on Windows. 


4) Yeah please do, just remember to test the `build` and `build-staging` commands, and then `npm start` which should give you a server on port 5000. Let me know if you have any questions on our build deploy process. Might be worthwhile for you to replicate our entire stack on your own heroku instances so can get a hang of all the pieces, but at the very least the frontend.

**Comment by andrewmarklloyd** [comment]
I think I have a solution that will be able to run the end-to-end tests using Travis CI and Docker. This will require a few updates to the `software-engineering-daily-api` project Travis CI job and the SE Daily Miner Heroku job. Here's what I'm thinking:

Prerequisites
---
These would be automated jobs:
- Get a latest dump of seeded database (happens when sedaily-miner Heroku cron job runs)
	- Run miner against running API instance
	- Run mongodump on the resulting DB
	- Upload output of mongodump to AWS S3
- Build `sedaily-mongo` image (triggered after successful sedaily-miner Heroku job runs)
	- Use mongodb as base image
	- Download latest mongodump from S3
	- Run mongorestore on db dump
	- Push image to Docker hub
- Build `sedaily-api` image and push to docker hub (happens on push to software-engineering-daily-api master branch)

Given all of the above, we would be able to do the following:
---
- `sedaily-frontend` runs end-to-end tests against latest API
	- Pull latest `sedaily-api` and `sedaily-mongo` images from Docker hub
	- Run API, mongo, and redis images in containers with docker-compose (similar to the `software-engineering-daily-api` docker-compose.yml file)
	- Execute end to end tests against Dockerized API

**Comment by andrewmarklloyd** [comment]
So i've manually created 2 Docker images: [`sedaily-rest-api`](https://hub.docker.com/r/andrewlloyd/sedaily-rest-api/) and [`sedaily-mongo`](https://hub.docker.com/r/andrewlloyd/sedaily-mongo/) and pushed them to the Docker hub under my namespace. In theory these two images will be under the SE Daily namespace and automatically built and pushed in the CI process from other projects.

I added a [docker-compose.yml](https://github.com/andrewmarklloyd/sedaily-front-end/blob/end-to-end-test/devops/docker-compose.yml) file to be used in the sedaily-fronted CI process. The workflow then is that [Travis CI](https://github.com/andrewmarklloyd/sedaily-front-end/blob/end-to-end-test/.travis.yml#L9) starts up the back end by pulling the latest Docker images for the API, Mongo, and Redis and runs a build that is configured to point to `http://localhost:4040/api` for API requests. Using @joshmorel's work as a model, the `start-server-and-test` command starts a server that serves the dist/ directory and waits for it to start before launching the cypress end-to-end tests.

All of that works locally and successfully runs the tests. However on Travis CI there is always an error for the tests: `CypressError: Timed out retrying: Expected to find element: '<element here>', but never found it.` It looks like cypress can't connect to `http://localhost:5000`. The good news is that I think this is just some config tweak and I think this will work out if we want to pursue it.

screen shot 2018-04-23 at 3 10 21 pm

**Comment by andrewmarklloyd** [comment]
Ok I got the build to pass. The problem was a really random one but it highlights the need for automated testing. Two components were importing `../utils/Post.util` instead of using the correct case `../utils/post.util`. This worked fine on my Mac because it's case insensitive. But running the build on Travis CI failed the build.

Here's the fix:

```
commit 16dda560c153f362af2d414ae4887c1d03061c18
Author: Andrew Lloyd <andrew85.lloyd@gmail.com>
Date:   Tue Apr 24 19:52:47 2018 -0700

    Use correct case to match post.utils file

diff --git a/src/components/ForumThreadBody.vue b/src/components/ForumThreadBody.vue
index 689766f..7e23311 100644
--- a/src/components/ForumThreadBody.vue
+++ b/src/components/ForumThreadBody.vue
@@ -26,7 +26,7 @@
 <script>
 import marked from 'marked'
 import PostSummary from '@/components/PostSummary.vue'
-import { postPrettyUrl } from './../utils/Post.utils'
+import { postPrettyUrl } from './../utils/post.utils'
 export default {
   name: 'form-thread-body',
   components: {
diff --git a/src/components/PostSummary.vue b/src/components/PostSummary.vue
index cd4af29..e6c3332 100644
--- a/src/components/PostSummary.vue
+++ b/src/components/PostSummary.vue
@@ -60,7 +60,7 @@
 <script>
 import moment from 'moment'
 import VotingArrows from 'components/VotingArrows'
-import { postPrettyUrl } from './../utils/Post.utils'
+import { postPrettyUrl } from './../utils/post.utils'
 import { PlayerState } from './../utils/playerState'
 import { mapActions, mapState } from 'vuex'
```

**Comment by joshmorel** [comment]
Yikes I never would have caught that because I'm on Linux. But for some reason I thought JavaScript/Node code would be case-sensitive regardless of OS. This would be run through Webpack... but I see this is a potential issue through a Google search and the rationale for [this library](https://github.com/Urthen/case-sensitive-paths-webpack-plugin).

Perhaps we should use it? The other option would [be linting](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) so long as linting is enforced on commits via Husky or similar.

**Comment by andrewmarklloyd** [comment]
Working on a [doc here](https://docs.google.com/document/d/1N9ljyHty76PF4iEpuVXOaxH_4U2KlEk_ODpGQtvNikw/edit?usp=sharing) to help explain the process:

**Comment by andrewmarklloyd** [comment]
@joshmorel I'll take a look this week

**Pull request merged**
