### PR TITLE
WIP: refactor testing and document process

### LINKED ISSUE #221: Clarify testing process
Hi - mentioned on Slack but figured I should formalize this issue.

README.md currently includes:

```md
# run selenium tests (working)
npm run selenium-test
```

However, files in `test/selenium` and the related `test/helpers` haven't been updates in 3 months.

On the other hand, `test/e2e` (itself a selenium abstraction using nightwatch) and `test/unit` have been updated and seem active parts of the project. 

My proposal:

* Remove `test/selenium` and `test/helpers` as well as the references in `package.json` and `README.md`.
* Update to reference README.md but also provide some guidelines on what functions should be tested and how

### PR DESCRIPTION
**Pull request by joshmorel**
To resolve #221

Didn't add clarity on what exactly needed a unit or integration/e2e test but removed the dead stuff and added a very simple line in README.md:

```markdown
# run tests (end-to-end and unit)
npm test
```

### CODE REVIEW

**Comment by jasonify** [comment]
Great thanks for doing this.  Let me know when you  feel it's ready and I can take a look and merge it in.

**Comment by joshmorel** [comment]
@jasonify I'm delving back into this during the weekend in conjunction with adding test coverage for jobs mvp. I have a few questions/comments for feedback in the interim.

A few things I noticed. Despite previous comments, it seems e2e folder hasn't really been updated since the project creation via vue-cli, so we could remove it and lose nothing. I also looked more through the history and noted you added selenium test files to tests to test login process I wouldn't want to remove it if it is important.

1) To confirm, is it still important?
2) If so I'm getting an error with `selenium-driver` v4. It seems we'd need to use 3.6 and define that in `package.json` (`after is not a function`)
3) If the purpose of `nightwatch` to provide an easier to use abstraction on top of selenium with more features, so wouldn't it make more sense to use that?

Anyways, let me know your thoughts. We could either maintain the selenium test, switch to nightwatch for integration tests or use unit tests only for now.

**Comment by jasonify** [comment]
I think those are all good points and questions.

 I would say that what we really need to look into is adding it to Travis CI if possible like we have on the backend.  If we aren't really running the tests it kind of defeats the purpose  of having them :(. An alternative would be to investigate push hooks (I know pre-commit hooks are common but that's too much I think).


I have no real attachment to either system, just was a little familiar with Selenium from past projects (and that was in Java either way). Sounds like it's basically the same stuff but nightwatch is more modern? Selenium driver can be annoying, so if we can simplify it lets do that 👍

**Comment by dfcook** [comment]
Is this PR just to remove the e2e tests?

As an aside, I don't know what's happened but if I get latest from develop the unit tests aren't working.

**Pull request closed without merging**
