### PR TITLE
Cherry pick style changes from Nuxt branch

### PR DESCRIPTION
**Pull request by dfcook**
Added styling changes to navbar and post view

### CODE REVIEW

**Comment by joshmorel** [comment]
Tried to figure it out the cause but gave up. I'll leave it to you - clicking on a category to filter collapses/distorts the category list in the new but not old (tried both Chrome & Firefox)

Otherwise I think it's okay?

**Comment by dfcook** [comment]
That should be sorted now

**Comment by joshmorel** [comment]
That issue is resolved and I can't find anything else glaring. I was't sure about the font change at first but now I like it. 

A few things to consider:

1)  Why change the logo to "SOFTWARE DAILY"? Both text and logo are fine IMHO, although although I would say that "Software Daily" is fine for the head title due to space limitations, but on the page should it not be spelled out in full - SOFTWARE ENGINEERING DAILY
2) The comments / related links side bar are nice additions, but given their addition, I feel they should be clickable to navigate to each section. I was also thinking fixed *might* be nice but it's hard to say so I wouldn't take time on that for now.

**Comment by jasonify** [comment]
Great. 

@joshmorel 
 1) I think we want to stay with Software Daily for all pages (eventual rebranding is the big picture I believe)  

2) Yeah that would be nice, just so they toggle which view you are seeing. I guess going back to the post content is something that would be missing.  We will be iterating more on design overall and polish. 

Seeing some errors but not sure they are a big deal:
```

webpack-internal:///2:1716 TypeError: Cannot read property 'isDeleted' of null
    at Proxy.render (EditJobView.vue?62a3:5)
    at VueComponent.Vue._render (webpack-internal:///2:4473)
    at VueComponent.updateComponent (webpack-internal:///2:2764)
    at Watcher.get (webpack-internal:///2:3114)
    at new Watcher (webpack-internal:///2:3103)
    at mountComponent (webpack-internal:///2:2771)
    at VueComponent.Vue$3.$mount (webpack-internal:///2:8428)
    at VueComponent.Vue$3.$mount (webpack-internal:///2:10789)
    at init (webpack-internal:///2:4064)
    at createComponent (webpack-internal:///2:5511)
logError @ webpack-internal:///2:1716
webpack-internal:///2:579 [Vue warn]: Error in render: "TypeError: Cannot read property 'title' of null"

found in

---> <JobView> at src/views/JobView.vue
       <App> at src/App.vue
         <Root>
warn @ webpack-internal:///2:579
webpack-internal:///2:1716 TypeError: Cannot read property 'title' of null
    at Proxy.render (JobView.vue?6b3c:9)
    at VueComponent.Vue._render (webpack-internal:///2:4473)
    at VueComponent.updateComponent (webpack-internal:///2:2764)
    at Watcher.get (webpack-internal:///2:3114)
    at new Watcher (webpack-internal:///2:3103)
    at mountComponent (webpack-internal:///2:2771)
    at VueComponent.Vue$3.$mount (webpack-internal:///2:8428)
    at VueComponent.Vue$3.$mount (webpack-internal:///2:10789)
    at init (webpack-internal:///2:4064)
    at createComponent (webpack-internal:///2:5511)
```

**Pull request merged**
