### PR TITLE
Submit auth enter

### LINKED ISSUE #59: On enter keyboard event should submit forms (Login, Register)

### PR DESCRIPTION
**Pull request by Canadauni**
PR to resolve #59. lt looks like when you have a button with a click handler the v-on:submit on the form element doesn't want to listen to an enter event. So I removed the v-on:click updated the login from a div to a form element. Let me know if there is anything you want changed.

### CODE REVIEW

**Comment by jasonify** [comment]
Thanks for looking into this.

I tested it out and it works great on the registration form, however it didn't seem to work for the login form (on keyboard press enter). I am using Chrome on OSX.

The Login button still works fine.

**Comment by Canadauni** [comment]
Hmm I'll have a look after work today. The two snippets look the same from what I can tell so it might be a little more involved than I first thought.

**Comment by Canadauni** [comment]
On my end it may have been because `type='username'` on the username input. I also tried to clean up some formatting to help match the register and login forms to help see why they might be acting differently. Hopefully this works on OSX.

**Comment by jasonify** [comment]
Looks good to me :)

**Pull request merged**
