### PR TITLE
User Profile Redesign v2.0

### PR DESCRIPTION
**Pull request by tyler-furby**
_Database entries have been made for this addition via [this Pull Request](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/pull/208)_

**Additions**
1. Users can now add social websites, such as GitHub, LinkedIn, Twitter
2. Users can now add a public email address
3. Users can now add an about summary to tell the community more about themselves and what they do.

**Left to go**
1. Adding current and previous projects with a tagging system noted in issue #427 
2. Validating URL's of user's GitHub, Twitter, LinkedIn links.
3. Validating public email address.

_Open to further suggestions..._

### CODE REVIEW

**Comment by tyler-furby** [comment]
@abdulbasitkay Hey! Thank you. I was thinking about the front end, as soon as you type something out of bounds it should issue an error, notifying the user to correct the URL. Also, I think bio should be changed to  'Headline' to be more clear, as the about section should be a paragraph or so about who you are and what you do.

**Comment by abdulbasitkay** [comment]
Thanks for the clarification @tyler-furby,
I also agree bio could be changed to Headline. It's much clearer this way. For the social media URLs, do you think we should just ask for usernames since they'll be easier to use for validation instead of the whole URL?

**Comment by joshmorel** [comment]
Noticed this in my email and I thought - huh, don't we already have a bio/about? But with the explanation, I agree with @abdulbasitkay - "headline" makes a lot more sense. Perhaps change the front-end labeling with this PR to make this clear? Otherwise, as a user I would be confused.

To make back-end, front-end and mobile consistent with variables naming, etc might be a bit more work but can be done later....

But good work @tyler-furby  - Social links are key!

**Comment by tyler-furby** [comment]
@joshmorel No problem, I'll change the variable names as well as the "bio" field to headline.

@abdulbasitkay We could probably just ask for usernames, though I think it would be even better if we can "authorize" these apps with Software Daily via GitHub's, Twitter's, and LinkedIn's API's.

**Comment by abdulbasitkay** [comment]
Exactly @tyler-furby, that's what I was thinking of.

**Comment by tyler-furby** [comment]
Let's continue the discussion at #449

**Pull request closed without merging**
