### PR TITLE
Chat integration 

### PR DESCRIPTION
**Pull request by edgar971**
This is the chat feature. Right now it's disabled with a flag, I will enable it once the chat server is deployed to a server. Feel free to make any code suggestions.

### CODE REVIEW

**Comment by crablar** [comment]
@edgar971 Should we wait until the chat server is deployed to merge this? Would be easier for us to test in that case.

**Comment by edgar971** [comment]
@crablar Yes, lets do that.

**Comment by edgar971** [comment]
Hi, the chat server is deployed and configured to work on the staging branch. This is ready to be tested.

**Comment by crablar** [comment]
Nice work @edgar971 . We are rolling out subscriptions this weekend which is a big release. @jasonify might not get to this until next week, but it's on our radar.

**Comment by jasonify** [comment]
Let's plan to get this in next week, thanks a ton for doing it @edgar971  :) 👍

**Comment by ghenry** [comment]
What made you select this chat method vs XMPP or integration with discordapp or slack etc?

**Comment by edgar971** [comment]
@ghenry We have more flexibility on how it works on the site and integrates with other SE Daily products. It's also an experiment, if it doesn't work out then we can remove it.

**Comment by ghenry** [comment]
Ah, no problem. I'm looking to add stanzo.io to our vuejs SPA so was
curious, but then we have a XMPP set up.

**Pull request merged**
