### PR TITLE
Auth and toast changes

### PR DESCRIPTION
**Pull request by dfcook**
Fixes include
#312 Change jobs board to jobs
#239 Set profile at point of authentication
#307 remove unneeded calls to fetch profile
#172 Use vue-toasted component for alerts

### CODE REVIEW

**Comment by joshmorel** [comment]
Thanks @dfcook - toast for messages is a good addition and much better than alerts!

A few things to resolve:

* `setMe` is not dispatched when registering
* the `fetchPublicProfileData` code also needs to be removed from `RegisterView`

**Comment by dfcook** [comment]
Good call, I thought the register action was fetching the profile, added this and changed RegisterView.

**Comment by joshmorel** [comment]
Looks good now!

**Comment by jasonify** [comment]
Hey, just started testing and  I am still seeing a slight bug with the profile page. The easiest way to reproduce it, refresh on http://localhost:8080/edit-profile 
All fields will be blank and getting this error:

```
[Vue warn]: Invalid prop: type check failed for prop "initialUsername". Expected String, got Undefined.

found in

---> <UpdateProfile> at src/components/UpdateProfile.vue
       <EditProfile> at src/views/EditProfileView.vue
         <App> at src/App.vue
           <Root>
```

Also, looks like we now have some merge conflicts sadly.

**Comment by dfcook** [comment]
I don't think this is a new issue, we've never protected our routes with authentication.

I've added a beforeEnter authorization hook to these routes:

- /edit-profile
- /add-job
- /edit-job
- /update-company
- /admin
- /admin/add-company
- /admin/edit-company

with a redirect to login if not authenticated.

Also merged conflicts.

**Comment by jasonify** [comment]
To clarify, I'm logged in when I refresh and it clears my form.

But yeah noticed the logged out thing too.

**Comment by dfcook** [comment]
Yes, my change fixed that as well, the code in edit-profile needed to wait for the profile load before rendering the sub-component.

**Comment by jasonify** [comment]
Everything looks great :)

**Pull request merged**
