### PR TITLE
Redesign Profile Page

### PR DESCRIPTION
**Pull request by tyler-furby**
This will be the first of many design changes to the profile page, here's an initial couple changes, this will resolve issue #336 :

**COMPLETED SO FAR**
1. Layout towards center instead of left aligned
2. Grow/Shrink when hovering over profile picture
3. User website changed to reflect the primary color of the website
4. Bold text for bio
5. `<hr/>` at end of profile details component
6. Moved `edit-link` to the top of the profile

**SUGGESTIONS**

1. Implementing a user _about_ section, to give more details about themselves and what they do.
2. Implementing a user _contact_ section, to provide a user's email address
3. Implementing a user's github, twitter, linkedin page in the form of font awesome icons
4. Implementing a user's _project_ section to include current and previous works

### CODE REVIEW

**Comment by crablar** [comment]
@tyler-furby I love all of these. The project section will need more scoping. I recommend linking up with @jasonify to brainstorm on that.

**Comment by tyler-furby** [comment]
@crablar Thanks, me and Jason talked about it, we were thinking about implementing tags, then these tagged posts could automatically get posted to the forums, and a search future to be able to look through these posts via elastic search or something of that nature.

**Comment by jasonify** [comment]
I really like the way the profile image grows :)

**Comment by crablar** [comment]
I like the idea of tags, since that is generally applicable to all forum posts. We are hoping the idea of "Post your projects on Software Daily" works out, but if it doesn't we could still use tags even if it becomes a general forum for technical subjects.

If the "Project Posting" theme works out, it would be great to have a dedicated "Projects" model, designs, etc

**Comment by tyler-furby** [comment]
**UPDATED**

https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/436

**Pull request merged**
