### PR TITLE
Snaz up contributers page with responsive styles

### PR DESCRIPTION
**Pull request by EmilyRosina**
- [x] remove double up in array
- [x] add github avatars
- [x] styling
- [x] responsivity
- [x] add link to "ping me" at bottom of page

### Preview
image

### CODE REVIEW

**Comment by crablar** [comment]
Nice work!!!

**Comment by crablar** [comment]
@EmilyRosina if you email me your info I'd be happy to send you a t-shirt for these amazing contributions

**Comment by jasonify** [comment]
Very cool! :D

**Comment by EmilyRosina** [comment]
Yay! Thanks guys :) glad you like the changes.

**Pull request merged**
