### PR TITLE
Update Chat Server URL and Enable Chat Component

### PR DESCRIPTION
**Pull request by edgar971**
@jasonify I fixed the chat server issues and updated the URL. You should be able to test it now. Let me know if you have any questions.

### CODE REVIEW

**Comment by crablar** [comment]
@edgar971 Jason is out of town this week but will be back by Monday. Sorry for unusual delay on PR review.

**Comment by jasonify** [comment]
Great, will take a look now that I'm back :)

**Comment by andrewmarklloyd** [comment]
@edgar971 I fixed the merge conflict in src/App.vue. There's an issue though that I believe is caused by either an API change, or something with how user's are handled on the front end. After you merge `develop` into your branch, run `npm run dev`, then you can test this issue:

Steps to reproduce: Login and see that the chat bar loads properly. With the developer console open in Chrome, logout, and then login. You will see the following error:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'name' of null"

found in

---> <ChatBox> at src/components/ChatBox.vue
       <App> at src/App.vue
         <Root>
```
screen shot 2018-03-27 at 8 27 43 pm

**Comment by andrewmarklloyd** [comment]
Looks like `me` is undefined in [ChatBox.vue](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/src/components/ChatBox.vue#L10)

**Comment by edgar971** [comment]
Was that removed from the store? Let me take a look.

**Comment by andrewmarklloyd** [comment]
So actually the issue is when you logout, and log back in, `state.me` is null, but immediately gets set after that. It's like a race condition, in [ChatBox](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/src/components/ChatBox.vue#L40), if you add `console.log(state.me)` before returning it, you'll see it.

**Comment by andrewmarklloyd** [comment]
Clicking Logout, calls `src/store/mutations.js` `setMe` function setting `state.me` to null

**Comment by edgar971** [comment]
Okay, the issues are fixed. I just check the `state` if `me` is set before rendering.

**Pull request closed without merging**
