### PR TITLE
Forum design v2

### PR DESCRIPTION
**Pull request by dfcook**
#362 #forum No Commets shows up but should show spinner first

Seems to work, as these are vuex actions and are triggered before the component is mounted I couldn't be certain. 

#347 New Forum Post - errors don't go away quickly.

Added data-vv-validate-on="input" to make validation happen as input changes.

#348 Avatar aspect ratio kept when made into circles

Made avatar image the background of a div rather than referenced directly.

#354 Change out compose thread icon 

Added attached icon

### CODE REVIEW

**Comment by dfcook** [comment]
#334 Usernames in Forum Comments Should Be Hyperlinks to User's Profile

Added for usernames in forum post meta and coments

**Comment by jasonify** [comment]
This is looking amazing :).

I'm seeing a small bug where if I write something on the content area and try to select all + delete it won't let me delete it. Even when just pressing backspace there seem to be some odd side effects (old text coming back instead of deleting).

**Comment by dfcook** [comment]
That should be sorted now, 2-way binding using :input was throwing out the validation.

**Comment by dfcook** [comment]
Also fixed:
#364 Reinstated favicon removed by merge
#365 Added deep CSS for anchor, we will need to do similar for all markdown as styles don't inherit into v-html

**Pull request merged**
