### PR TITLE
Clicking Links From Forum Posts Should Open New Tab #433

### PR DESCRIPTION
**Pull request by dasimandl**

### CODE REVIEW

**Comment by dasimandl** [comment]
implemented regex to append target="_blank" to rendered markdown

**Comment by andrewmarklloyd** [comment]
This doesn't seem to be working yet. Here's the review app I tested on: https://sedaily-frontend-stagin-pr-565.herokuapp.com/forum/5b1a68f6b6e8ff00048aa148

**Comment by dasimandl** [comment]
@andrewmarklloyd So that is not a "Link" that is an internal frontend route.  Checkout this post that has an outside link.  It opens up in a new tab.  https://sedaily-frontend-stagin-pr-565.herokuapp.com/forum/5bb346e32693c50029056317

**Comment by andrewmarklloyd** [comment]
@dasimandl I was talking about the https://www.investopedia.com/ask/answers/05/economicmoat.asp link on that page. There's also several examples here: https://sedaily-frontend-stagin-pr-565.herokuapp.com/forum/5ab44c224039e5002a4d0425

**Comment by andrewmarklloyd** [comment]
Looks like you're right, it's only on comments that the link doesn't open in a new tab. The related links look like they are working correctly. Here's an example: https://sedaily-frontend-stagin-pr-565.herokuapp.com/post/59addb05f47a6d53a934cf55/Information-Theory-with-Jimmy-Soni-and-Rob-Goodman

**Comment by dasimandl** [comment]
@andrewmarklloyd updated CommentView component to update markedDown links to open to new tab.  The example link that you provided above now works.

**Pull request merged**
